# Generated by Django 4.2.4 on 2023-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='technology_card_image')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_avatar', models.ImageField(upload_to='client_avatar')),
                ('client_designation', models.CharField(max_length=30)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle',models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='main_section_banner_image')),
            ],
        ),
        migrations.CreateModel(
            name='RaiseQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=40)),
                ('service', models.CharField(max_length=50)),
                ('enquiry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_in_life_science', models.PositiveIntegerField()),
                ('countries_reached', models.PositiveIntegerField()),
                ('companies_onboarded', models.PositiveIntegerField()),
                ('satisfied_reach', models.PositiveIntegerField()),
                ('experienced', models.PositiveIntegerField()),
            ],
        ),
    ]
