# Generated by Django 4.2.4 on 2023-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_alter_mainbanner_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='icon',
            field=models.ImageField(upload_to='main_section_icon_image'),
        ),
    ]
