# Generated by Django 4.2.4 on 2023-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_mainbanner_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsections',
            name='link',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
